### ISSUE TITLE
Throws 'not found' error upon loading

### ISSUE THREAD

**Issue by naconner** [lamassu/lamassu-bitgo#8]
Upon configuring credentials and loading in lamassu-server@2.2.5, module throws error:

```
[2015-03-30T18:23:33.742Z] DEBUG: lamassu-server/25281 on lamassu-bitgo-5: plugin(ticker) loaded: Bitpay
[2015-03-30T18:23:33.876Z] DEBUG: lamassu-server/25281 on lamassu-bitgo-5: plugin(transfer) loaded: BitGo
[2015-03-30T18:23:34.245Z] ERROR: lamassu-server/25281 on lamassu-bitgo-5: not found
    Error: not found
        at errFromResponse (/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-bitgo/node_modules/bitgo/src/bitgo.js:57:15)
        at /usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-bitgo/node_modules/bitgo/src/bitgo.js:70:13
        at _fulfilled (/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-bitgo/node_modules/bitgo/node_modules/q/q.js:794:54)
        at self.promiseDispatch.done (/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-bitgo/node_modules/bitgo/node_modules/q/q.js:823:30)
        at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-bitgo/node_modules/bitgo/node_modules/q/q.js:756:13)
        at /usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-bitgo/node_modules/bitgo/node_modules/q/q.js:564:44
        at flush (/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-bitgo/node_modules/bitgo/node_modules/q/q.js:110:17)
        at process._tickCallback (node.js:419:13)
[2015-03-30T18:23:35.484Z] DEBUG: lamassu-server/25281 on lamassu-bitgo-5: poll request from: 3A:7F:96:4F:BD:BA:4B:BC:EA:66:FB:D8:9F:1C:66:F6:D5:63:93:08
```

Contents of `bitgo.js`: https://gist.github.com/naconner/35722796c19fe8588702#file-gistfile1-txt-L57

`lamassu-bitgo`'s package fixes the `bitgo` dependency at 0.9.21, though I'm receiving the same error when upgrading `bitgo` to 0.9.26.

**Comment by naconner** [comment]
Above was due to using an incorrect address as the wallet ID. Closing.
